# Generated by Django 5.2.4 on 2025-07-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('artist', models.CharField(max_length=300)),
                ('gerne', models.CharField(max_length=300)),
                ('audio_url', models.CharField(max_length=300)),
                ('duration', models.CharField(max_length=300)),
                ('cover_image', models.ImageField(blank=True, upload_to='cover_image/')),
            ],
        ),
    ]
