# Generated by Django 5.2.4 on 2025-08-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0003_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_image', models.ImageField(blank=True, upload_to='artist_image/')),
                ('artist_name', models.CharField(max_length=55)),
            ],
        ),
    ]
