# Generated by Django 5.2.4 on 2025-08-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0006_artist_remove_song_artist_image_alter_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Name_artist',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
