# Generated by Django 5.2.4 on 2025-08-02 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0008_remove_artist_name_artist_alter_artist_artist_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(default='Unknown Artist', max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_image/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='Spotify.artist'),
            preserve_default=False,
        ),
    ]
