# Generated by Django 5.2.4 on 2025-08-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
