# Generated by Django 5.2.4 on 2025-08-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0004_artist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.AddField(
            model_name='song',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_image/'),
        ),
    ]
