# Generated by Django 5.2.4 on 2025-08-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0005_delete_artist_song_artist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_image', models.ImageField(blank=True, null=True, upload_to='artist_image/')),
                ('Name_artist', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist_image',
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='Spotify.artist'),
        ),
    ]
