# Generated by Django 5.2.4 on 2025-08-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0007_alter_artist_name_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='Name_artist',
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(blank=True, upload_to='artist_image/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
