# Generated by Django 5.2.4 on 2025-08-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0009_artist_name_alter_artist_artist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='gerne',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
